void PhotonConversion()
{
//=========Macro generated from canvas: PhotonConversion/PhotonConversion
//=========  (Fri May 29 13:58:07 2020) by ROOT version 6.16/00
   TCanvas *PhotonConversion = new TCanvas("PhotonConversion", "PhotonConversion",0,0,1000,1000);
   gStyle->SetOptFit(1);
   gStyle->SetOptStat(0);
   gStyle->SetOptTitle(0);
   PhotonConversion->SetHighLightColor(2);
   PhotonConversion->Range(0,0,1,1);
   PhotonConversion->SetFillColor(0);
   PhotonConversion->SetBorderMode(0);
   PhotonConversion->SetBorderSize(2);
   PhotonConversion->SetTickx(1);
   PhotonConversion->SetTicky(1);
   PhotonConversion->SetLeftMargin(0.16);
   PhotonConversion->SetRightMargin(0.05);
   PhotonConversion->SetTopMargin(0.05);
   PhotonConversion->SetBottomMargin(0.16);
   PhotonConversion->SetFrameBorderMode(0);
  
// ------------>Primitives in pad: PhotonConversion_1
   TPad *PhotonConversion_1 = new TPad("PhotonConversion_1", "PhotonConversion_1",0.01,0.01,0.99,0.99);
   PhotonConversion_1->Draw();
   PhotonConversion_1->cd();
   PhotonConversion_1->Range(-0.2025316,-0.08061359,1.063291,6.067534);
   PhotonConversion_1->SetFillColor(0);
   PhotonConversion_1->SetBorderMode(0);
   PhotonConversion_1->SetBorderSize(2);
   PhotonConversion_1->SetLogy();
   PhotonConversion_1->SetTickx(1);
   PhotonConversion_1->SetTicky(1);
   PhotonConversion_1->SetLeftMargin(0.16);
   PhotonConversion_1->SetRightMargin(0.05);
   PhotonConversion_1->SetTopMargin(0.05);
   PhotonConversion_1->SetBottomMargin(0.16);
   PhotonConversion_1->SetFrameBorderMode(0);
   PhotonConversion_1->SetFrameBorderMode(0);
   
   TH1D *hPhotonSiliconConverted__5 = new TH1D("hPhotonSiliconConverted__5","",100,0,1);
   hPhotonSiliconConverted__5->SetBinContent(1,7327);
   hPhotonSiliconConverted__5->SetBinContent(2,6216);
   hPhotonSiliconConverted__5->SetBinContent(3,5293);
   hPhotonSiliconConverted__5->SetBinContent(4,4853);
   hPhotonSiliconConverted__5->SetBinContent(5,4388);
   hPhotonSiliconConverted__5->SetBinContent(6,4173);
   hPhotonSiliconConverted__5->SetBinContent(7,4025);
   hPhotonSiliconConverted__5->SetBinContent(8,3842);
   hPhotonSiliconConverted__5->SetBinContent(9,3541);
   hPhotonSiliconConverted__5->SetBinContent(10,3571);
   hPhotonSiliconConverted__5->SetBinContent(11,3226);
   hPhotonSiliconConverted__5->SetBinContent(12,3108);
   hPhotonSiliconConverted__5->SetBinContent(13,2873);
   hPhotonSiliconConverted__5->SetBinContent(14,2722);
   hPhotonSiliconConverted__5->SetBinContent(15,2630);
   hPhotonSiliconConverted__5->SetBinContent(16,2421);
   hPhotonSiliconConverted__5->SetBinContent(17,2358);
   hPhotonSiliconConverted__5->SetBinContent(18,2169);
   hPhotonSiliconConverted__5->SetBinContent(19,2045);
   hPhotonSiliconConverted__5->SetBinContent(20,1873);
   hPhotonSiliconConverted__5->SetBinContent(21,1655);
   hPhotonSiliconConverted__5->SetBinContent(22,1545);
   hPhotonSiliconConverted__5->SetBinContent(23,1294);
   hPhotonSiliconConverted__5->SetBinContent(24,1155);
   hPhotonSiliconConverted__5->SetBinContent(25,914);
   hPhotonSiliconConverted__5->SetBinContent(26,687);
   hPhotonSiliconConverted__5->SetBinContent(27,477);
   hPhotonSiliconConverted__5->SetBinContent(28,253);
   hPhotonSiliconConverted__5->SetBinContent(29,109);
   hPhotonSiliconConverted__5->SetBinContent(30,81);
   hPhotonSiliconConverted__5->SetBinContent(31,96);
   hPhotonSiliconConverted__5->SetBinContent(32,95);
   hPhotonSiliconConverted__5->SetBinContent(33,81);
   hPhotonSiliconConverted__5->SetBinContent(34,82);
   hPhotonSiliconConverted__5->SetBinContent(35,84);
   hPhotonSiliconConverted__5->SetBinContent(36,72);
   hPhotonSiliconConverted__5->SetBinContent(37,63);
   hPhotonSiliconConverted__5->SetBinContent(38,50);
   hPhotonSiliconConverted__5->SetBinContent(39,55);
   hPhotonSiliconConverted__5->SetBinContent(40,45);
   hPhotonSiliconConverted__5->SetBinContent(41,42);
   hPhotonSiliconConverted__5->SetBinContent(42,66);
   hPhotonSiliconConverted__5->SetBinContent(43,41);
   hPhotonSiliconConverted__5->SetBinContent(44,54);
   hPhotonSiliconConverted__5->SetBinContent(45,49);
   hPhotonSiliconConverted__5->SetBinContent(46,47);
   hPhotonSiliconConverted__5->SetBinContent(47,30);
   hPhotonSiliconConverted__5->SetBinContent(48,51);
   hPhotonSiliconConverted__5->SetBinContent(49,52);
   hPhotonSiliconConverted__5->SetBinContent(50,49);
   hPhotonSiliconConverted__5->SetBinContent(51,45);
   hPhotonSiliconConverted__5->SetBinContent(52,34);
   hPhotonSiliconConverted__5->SetBinContent(53,42);
   hPhotonSiliconConverted__5->SetBinContent(54,25);
   hPhotonSiliconConverted__5->SetBinContent(55,35);
   hPhotonSiliconConverted__5->SetBinContent(56,36);
   hPhotonSiliconConverted__5->SetBinContent(57,32);
   hPhotonSiliconConverted__5->SetBinContent(58,43);
   hPhotonSiliconConverted__5->SetBinContent(59,38);
   hPhotonSiliconConverted__5->SetBinContent(60,33);
   hPhotonSiliconConverted__5->SetBinContent(61,38);
   hPhotonSiliconConverted__5->SetBinContent(62,28);
   hPhotonSiliconConverted__5->SetBinContent(63,33);
   hPhotonSiliconConverted__5->SetBinContent(64,22);
   hPhotonSiliconConverted__5->SetBinContent(65,27);
   hPhotonSiliconConverted__5->SetBinContent(66,26);
   hPhotonSiliconConverted__5->SetBinContent(67,28);
   hPhotonSiliconConverted__5->SetBinContent(68,33);
   hPhotonSiliconConverted__5->SetBinContent(69,16);
   hPhotonSiliconConverted__5->SetBinContent(70,30);
   hPhotonSiliconConverted__5->SetBinContent(71,31);
   hPhotonSiliconConverted__5->SetBinContent(72,19);
   hPhotonSiliconConverted__5->SetBinContent(73,25);
   hPhotonSiliconConverted__5->SetBinContent(74,29);
   hPhotonSiliconConverted__5->SetBinContent(75,28);
   hPhotonSiliconConverted__5->SetBinContent(76,22);
   hPhotonSiliconConverted__5->SetBinContent(77,29);
   hPhotonSiliconConverted__5->SetBinContent(78,24);
   hPhotonSiliconConverted__5->SetBinContent(79,25);
   hPhotonSiliconConverted__5->SetBinContent(80,21);
   hPhotonSiliconConverted__5->SetBinContent(81,20);
   hPhotonSiliconConverted__5->SetBinContent(82,17);
   hPhotonSiliconConverted__5->SetBinContent(83,33);
   hPhotonSiliconConverted__5->SetBinContent(84,27);
   hPhotonSiliconConverted__5->SetBinContent(85,46);
   hPhotonSiliconConverted__5->SetBinContent(86,69);
   hPhotonSiliconConverted__5->SetBinContent(87,73);
   hPhotonSiliconConverted__5->SetBinContent(88,93);
   hPhotonSiliconConverted__5->SetBinContent(89,148);
   hPhotonSiliconConverted__5->SetBinContent(90,167);
   hPhotonSiliconConverted__5->SetBinContent(91,208);
   hPhotonSiliconConverted__5->SetBinContent(92,266);
   hPhotonSiliconConverted__5->SetBinContent(93,349);
   hPhotonSiliconConverted__5->SetBinContent(94,465);
   hPhotonSiliconConverted__5->SetBinContent(95,615);
   hPhotonSiliconConverted__5->SetBinContent(96,904);
   hPhotonSiliconConverted__5->SetBinContent(97,1138);
   hPhotonSiliconConverted__5->SetBinContent(98,1627);
   hPhotonSiliconConverted__5->SetBinContent(99,2391);
   hPhotonSiliconConverted__5->SetBinContent(100,303793);
   hPhotonSiliconConverted__5->SetBinContent(101,379248);
   hPhotonSiliconConverted__5->SetEntries(774622);

   Int_t ci;      // for color index setting
   TColor *color; // for color definition with alpha
   ci = 1184;
   color = new TColor(ci, 0, 0, 0.6, " ", 0.3);
   hPhotonSiliconConverted__5->SetFillColor(ci);

   ci = TColor::GetColor("#000099");
   hPhotonSiliconConverted__5->SetLineColor(ci);
   hPhotonSiliconConverted__5->SetLineWidth(2);
   hPhotonSiliconConverted__5->SetMarkerStyle(20);
   hPhotonSiliconConverted__5->SetMarkerSize(1.2);
   hPhotonSiliconConverted__5->GetXaxis()->SetTitle("Fraction of photon energy ionized");
   hPhotonSiliconConverted__5->GetXaxis()->SetLabelFont(42);
   hPhotonSiliconConverted__5->GetXaxis()->SetLabelSize(0.05);
   hPhotonSiliconConverted__5->GetXaxis()->SetTitleSize(0.05);
   hPhotonSiliconConverted__5->GetXaxis()->SetTitleOffset(1.4);
   hPhotonSiliconConverted__5->GetXaxis()->SetTitleFont(42);
   hPhotonSiliconConverted__5->GetYaxis()->SetLabelFont(42);
   hPhotonSiliconConverted__5->GetYaxis()->SetLabelSize(0.05);
   hPhotonSiliconConverted__5->GetYaxis()->SetTitleSize(0.05);
   hPhotonSiliconConverted__5->GetYaxis()->SetTitleOffset(1.4);
   hPhotonSiliconConverted__5->GetYaxis()->SetTitleFont(42);
   hPhotonSiliconConverted__5->GetZaxis()->SetLabelFont(42);
   hPhotonSiliconConverted__5->GetZaxis()->SetLabelSize(0.05);
   hPhotonSiliconConverted__5->GetZaxis()->SetTitleSize(0.05);
   hPhotonSiliconConverted__5->GetZaxis()->SetTitleOffset(1);
   hPhotonSiliconConverted__5->GetZaxis()->SetTitleFont(42);
   hPhotonSiliconConverted__5->Draw("");
   
   TH1D *hPhotonBeConverted__6 = new TH1D("hPhotonBeConverted__6","",100,0,1);
   hPhotonBeConverted__6->SetBinContent(1,16626);
   hPhotonBeConverted__6->SetBinContent(2,14052);
   hPhotonBeConverted__6->SetBinContent(3,12460);
   hPhotonBeConverted__6->SetBinContent(4,11260);
   hPhotonBeConverted__6->SetBinContent(5,10292);
   hPhotonBeConverted__6->SetBinContent(6,9307);
   hPhotonBeConverted__6->SetBinContent(7,8755);
   hPhotonBeConverted__6->SetBinContent(8,8018);
   hPhotonBeConverted__6->SetBinContent(9,7522);
   hPhotonBeConverted__6->SetBinContent(10,7005);
   hPhotonBeConverted__6->SetBinContent(11,6663);
   hPhotonBeConverted__6->SetBinContent(12,6245);
   hPhotonBeConverted__6->SetBinContent(13,5772);
   hPhotonBeConverted__6->SetBinContent(14,5484);
   hPhotonBeConverted__6->SetBinContent(15,5134);
   hPhotonBeConverted__6->SetBinContent(16,4809);
   hPhotonBeConverted__6->SetBinContent(17,4590);
   hPhotonBeConverted__6->SetBinContent(18,4296);
   hPhotonBeConverted__6->SetBinContent(19,3929);
   hPhotonBeConverted__6->SetBinContent(20,3654);
   hPhotonBeConverted__6->SetBinContent(21,3208);
   hPhotonBeConverted__6->SetBinContent(22,2946);
   hPhotonBeConverted__6->SetBinContent(23,2613);
   hPhotonBeConverted__6->SetBinContent(24,2368);
   hPhotonBeConverted__6->SetBinContent(25,1954);
   hPhotonBeConverted__6->SetBinContent(26,1572);
   hPhotonBeConverted__6->SetBinContent(27,1164);
   hPhotonBeConverted__6->SetBinContent(28,718);
   hPhotonBeConverted__6->SetBinContent(29,425);
   hPhotonBeConverted__6->SetBinContent(30,434);
   hPhotonBeConverted__6->SetBinContent(31,433);
   hPhotonBeConverted__6->SetBinContent(32,412);
   hPhotonBeConverted__6->SetBinContent(33,413);
   hPhotonBeConverted__6->SetBinContent(34,462);
   hPhotonBeConverted__6->SetBinContent(35,451);
   hPhotonBeConverted__6->SetBinContent(36,419);
   hPhotonBeConverted__6->SetBinContent(37,401);
   hPhotonBeConverted__6->SetBinContent(38,468);
   hPhotonBeConverted__6->SetBinContent(39,393);
   hPhotonBeConverted__6->SetBinContent(40,430);
   hPhotonBeConverted__6->SetBinContent(41,425);
   hPhotonBeConverted__6->SetBinContent(42,445);
   hPhotonBeConverted__6->SetBinContent(43,478);
   hPhotonBeConverted__6->SetBinContent(44,444);
   hPhotonBeConverted__6->SetBinContent(45,505);
   hPhotonBeConverted__6->SetBinContent(46,479);
   hPhotonBeConverted__6->SetBinContent(47,485);
   hPhotonBeConverted__6->SetBinContent(48,483);
   hPhotonBeConverted__6->SetBinContent(49,496);
   hPhotonBeConverted__6->SetBinContent(50,531);
   hPhotonBeConverted__6->SetBinContent(51,472);
   hPhotonBeConverted__6->SetBinContent(52,558);
   hPhotonBeConverted__6->SetBinContent(53,554);
   hPhotonBeConverted__6->SetBinContent(54,527);
   hPhotonBeConverted__6->SetBinContent(55,509);
   hPhotonBeConverted__6->SetBinContent(56,543);
   hPhotonBeConverted__6->SetBinContent(57,475);
   hPhotonBeConverted__6->SetBinContent(58,560);
   hPhotonBeConverted__6->SetBinContent(59,609);
   hPhotonBeConverted__6->SetBinContent(60,599);
   hPhotonBeConverted__6->SetBinContent(61,609);
   hPhotonBeConverted__6->SetBinContent(62,535);
   hPhotonBeConverted__6->SetBinContent(63,525);
   hPhotonBeConverted__6->SetBinContent(64,574);
   hPhotonBeConverted__6->SetBinContent(65,598);
   hPhotonBeConverted__6->SetBinContent(66,596);
   hPhotonBeConverted__6->SetBinContent(67,535);
   hPhotonBeConverted__6->SetBinContent(68,578);
   hPhotonBeConverted__6->SetBinContent(69,542);
   hPhotonBeConverted__6->SetBinContent(70,537);
   hPhotonBeConverted__6->SetBinContent(71,510);
   hPhotonBeConverted__6->SetBinContent(72,507);
   hPhotonBeConverted__6->SetBinContent(73,474);
   hPhotonBeConverted__6->SetBinContent(74,423);
   hPhotonBeConverted__6->SetBinContent(75,469);
   hPhotonBeConverted__6->SetBinContent(76,447);
   hPhotonBeConverted__6->SetBinContent(77,386);
   hPhotonBeConverted__6->SetBinContent(78,348);
   hPhotonBeConverted__6->SetBinContent(79,328);
   hPhotonBeConverted__6->SetBinContent(80,274);
   hPhotonBeConverted__6->SetBinContent(81,191);
   hPhotonBeConverted__6->SetBinContent(82,130);
   hPhotonBeConverted__6->SetBinContent(83,35);
   hPhotonBeConverted__6->SetBinContent(84,31);
   hPhotonBeConverted__6->SetBinContent(85,33);
   hPhotonBeConverted__6->SetBinContent(86,25);
   hPhotonBeConverted__6->SetBinContent(87,23);
   hPhotonBeConverted__6->SetBinContent(88,22);
   hPhotonBeConverted__6->SetBinContent(89,16);
   hPhotonBeConverted__6->SetBinContent(90,24);
   hPhotonBeConverted__6->SetBinContent(91,18);
   hPhotonBeConverted__6->SetBinContent(92,19);
   hPhotonBeConverted__6->SetBinContent(93,22);
   hPhotonBeConverted__6->SetBinContent(94,18);
   hPhotonBeConverted__6->SetBinContent(95,25);
   hPhotonBeConverted__6->SetBinContent(96,24);
   hPhotonBeConverted__6->SetBinContent(97,21);
   hPhotonBeConverted__6->SetBinContent(98,21);
   hPhotonBeConverted__6->SetBinContent(99,6);
   hPhotonBeConverted__6->SetBinContent(100,20494);
   hPhotonBeConverted__6->SetBinContent(101,20255);
   hPhotonBeConverted__6->SetEntries(238982);

   ci = 1183;
   color = new TColor(ci, 0, 0.6, 0, " ", 0.3);
   hPhotonBeConverted__6->SetFillColor(ci);

   ci = TColor::GetColor("#009900");
   hPhotonBeConverted__6->SetLineColor(ci);
   hPhotonBeConverted__6->SetLineWidth(2);
   hPhotonBeConverted__6->SetMarkerStyle(20);
   hPhotonBeConverted__6->SetMarkerSize(1.2);
   hPhotonBeConverted__6->GetXaxis()->SetTitle("Fraction of photon energy ionized");
   hPhotonBeConverted__6->GetXaxis()->SetLabelFont(42);
   hPhotonBeConverted__6->GetXaxis()->SetLabelSize(0.05);
   hPhotonBeConverted__6->GetXaxis()->SetTitleSize(0.05);
   hPhotonBeConverted__6->GetXaxis()->SetTitleOffset(1.4);
   hPhotonBeConverted__6->GetXaxis()->SetTitleFont(42);
   hPhotonBeConverted__6->GetYaxis()->SetLabelFont(42);
   hPhotonBeConverted__6->GetYaxis()->SetLabelSize(0.05);
   hPhotonBeConverted__6->GetYaxis()->SetTitleSize(0.05);
   hPhotonBeConverted__6->GetYaxis()->SetTitleOffset(1.4);
   hPhotonBeConverted__6->GetYaxis()->SetTitleFont(42);
   hPhotonBeConverted__6->GetZaxis()->SetLabelFont(42);
   hPhotonBeConverted__6->GetZaxis()->SetLabelSize(0.05);
   hPhotonBeConverted__6->GetZaxis()->SetTitleSize(0.05);
   hPhotonBeConverted__6->GetZaxis()->SetTitleOffset(1);
   hPhotonBeConverted__6->GetZaxis()->SetTitleFont(42);
   hPhotonBeConverted__6->Draw("same");
   
   TH1D *hPhotonAuConverted__7 = new TH1D("hPhotonAuConverted__7","",100,0,1);
   hPhotonAuConverted__7->SetBinContent(1,300);
   hPhotonAuConverted__7->SetBinContent(2,255);
   hPhotonAuConverted__7->SetBinContent(3,233);
   hPhotonAuConverted__7->SetBinContent(4,198);
   hPhotonAuConverted__7->SetBinContent(5,170);
   hPhotonAuConverted__7->SetBinContent(6,147);
   hPhotonAuConverted__7->SetBinContent(7,136);
   hPhotonAuConverted__7->SetBinContent(8,154);
   hPhotonAuConverted__7->SetBinContent(9,132);
   hPhotonAuConverted__7->SetBinContent(10,121);
   hPhotonAuConverted__7->SetBinContent(11,101);
   hPhotonAuConverted__7->SetBinContent(12,119);
   hPhotonAuConverted__7->SetBinContent(13,97);
   hPhotonAuConverted__7->SetBinContent(14,106);
   hPhotonAuConverted__7->SetBinContent(15,75);
   hPhotonAuConverted__7->SetBinContent(16,92);
   hPhotonAuConverted__7->SetBinContent(17,102);
   hPhotonAuConverted__7->SetBinContent(18,111);
   hPhotonAuConverted__7->SetBinContent(19,189);
   hPhotonAuConverted__7->SetBinContent(20,281);
   hPhotonAuConverted__7->SetBinContent(21,352);
   hPhotonAuConverted__7->SetBinContent(22,454);
   hPhotonAuConverted__7->SetBinContent(23,471);
   hPhotonAuConverted__7->SetBinContent(24,543);
   hPhotonAuConverted__7->SetBinContent(25,647);
   hPhotonAuConverted__7->SetBinContent(26,656);
   hPhotonAuConverted__7->SetBinContent(27,632);
   hPhotonAuConverted__7->SetBinContent(28,697);
   hPhotonAuConverted__7->SetBinContent(29,771);
   hPhotonAuConverted__7->SetBinContent(30,752);
   hPhotonAuConverted__7->SetBinContent(31,781);
   hPhotonAuConverted__7->SetBinContent(32,824);
   hPhotonAuConverted__7->SetBinContent(33,892);
   hPhotonAuConverted__7->SetBinContent(34,885);
   hPhotonAuConverted__7->SetBinContent(35,938);
   hPhotonAuConverted__7->SetBinContent(36,941);
   hPhotonAuConverted__7->SetBinContent(37,922);
   hPhotonAuConverted__7->SetBinContent(38,937);
   hPhotonAuConverted__7->SetBinContent(39,907);
   hPhotonAuConverted__7->SetBinContent(40,975);
   hPhotonAuConverted__7->SetBinContent(41,988);
   hPhotonAuConverted__7->SetBinContent(42,993);
   hPhotonAuConverted__7->SetBinContent(43,958);
   hPhotonAuConverted__7->SetBinContent(44,876);
   hPhotonAuConverted__7->SetBinContent(45,981);
   hPhotonAuConverted__7->SetBinContent(46,913);
   hPhotonAuConverted__7->SetBinContent(47,969);
   hPhotonAuConverted__7->SetBinContent(48,919);
   hPhotonAuConverted__7->SetBinContent(49,982);
   hPhotonAuConverted__7->SetBinContent(50,860);
   hPhotonAuConverted__7->SetBinContent(51,910);
   hPhotonAuConverted__7->SetBinContent(52,893);
   hPhotonAuConverted__7->SetBinContent(53,879);
   hPhotonAuConverted__7->SetBinContent(54,855);
   hPhotonAuConverted__7->SetBinContent(55,832);
   hPhotonAuConverted__7->SetBinContent(56,880);
   hPhotonAuConverted__7->SetBinContent(57,833);
   hPhotonAuConverted__7->SetBinContent(58,874);
   hPhotonAuConverted__7->SetBinContent(59,806);
   hPhotonAuConverted__7->SetBinContent(60,782);
   hPhotonAuConverted__7->SetBinContent(61,797);
   hPhotonAuConverted__7->SetBinContent(62,755);
   hPhotonAuConverted__7->SetBinContent(63,788);
   hPhotonAuConverted__7->SetBinContent(64,754);
   hPhotonAuConverted__7->SetBinContent(65,754);
   hPhotonAuConverted__7->SetBinContent(66,680);
   hPhotonAuConverted__7->SetBinContent(67,706);
   hPhotonAuConverted__7->SetBinContent(68,647);
   hPhotonAuConverted__7->SetBinContent(69,639);
   hPhotonAuConverted__7->SetBinContent(70,648);
   hPhotonAuConverted__7->SetBinContent(71,632);
   hPhotonAuConverted__7->SetBinContent(72,605);
   hPhotonAuConverted__7->SetBinContent(73,566);
   hPhotonAuConverted__7->SetBinContent(74,550);
   hPhotonAuConverted__7->SetBinContent(75,551);
   hPhotonAuConverted__7->SetBinContent(76,590);
   hPhotonAuConverted__7->SetBinContent(77,576);
   hPhotonAuConverted__7->SetBinContent(78,535);
   hPhotonAuConverted__7->SetBinContent(79,497);
   hPhotonAuConverted__7->SetBinContent(80,473);
   hPhotonAuConverted__7->SetBinContent(81,531);
   hPhotonAuConverted__7->SetBinContent(82,544);
   hPhotonAuConverted__7->SetBinContent(83,623);
   hPhotonAuConverted__7->SetBinContent(84,727);
   hPhotonAuConverted__7->SetBinContent(85,663);
   hPhotonAuConverted__7->SetBinContent(86,739);
   hPhotonAuConverted__7->SetBinContent(87,784);
   hPhotonAuConverted__7->SetBinContent(88,874);
   hPhotonAuConverted__7->SetBinContent(89,957);
   hPhotonAuConverted__7->SetBinContent(90,1077);
   hPhotonAuConverted__7->SetBinContent(91,1279);
   hPhotonAuConverted__7->SetBinContent(92,1431);
   hPhotonAuConverted__7->SetBinContent(93,1694);
   hPhotonAuConverted__7->SetBinContent(94,2008);
   hPhotonAuConverted__7->SetBinContent(95,2103);
   hPhotonAuConverted__7->SetBinContent(96,1898);
   hPhotonAuConverted__7->SetBinContent(97,1498);
   hPhotonAuConverted__7->SetBinContent(98,1074);
   hPhotonAuConverted__7->SetBinContent(99,255);
   hPhotonAuConverted__7->SetBinContent(100,668525);
   hPhotonAuConverted__7->SetBinContent(101,805852);
   hPhotonAuConverted__7->SetEntries(1543958);

   ci = 1182;
   color = new TColor(ci, 0.6, 0, 0, " ", 0.3);
   hPhotonAuConverted__7->SetFillColor(ci);

   ci = TColor::GetColor("#990000");
   hPhotonAuConverted__7->SetLineColor(ci);
   hPhotonAuConverted__7->SetLineWidth(2);
   hPhotonAuConverted__7->SetMarkerStyle(20);
   hPhotonAuConverted__7->SetMarkerSize(1.2);
   hPhotonAuConverted__7->GetXaxis()->SetTitle("Fraction of photon energy ionized");
   hPhotonAuConverted__7->GetXaxis()->SetLabelFont(42);
   hPhotonAuConverted__7->GetXaxis()->SetLabelSize(0.05);
   hPhotonAuConverted__7->GetXaxis()->SetTitleSize(0.05);
   hPhotonAuConverted__7->GetXaxis()->SetTitleOffset(1.4);
   hPhotonAuConverted__7->GetXaxis()->SetTitleFont(42);
   hPhotonAuConverted__7->GetYaxis()->SetLabelFont(42);
   hPhotonAuConverted__7->GetYaxis()->SetLabelSize(0.05);
   hPhotonAuConverted__7->GetYaxis()->SetTitleSize(0.05);
   hPhotonAuConverted__7->GetYaxis()->SetTitleOffset(1.4);
   hPhotonAuConverted__7->GetYaxis()->SetTitleFont(42);
   hPhotonAuConverted__7->GetZaxis()->SetLabelFont(42);
   hPhotonAuConverted__7->GetZaxis()->SetLabelSize(0.05);
   hPhotonAuConverted__7->GetZaxis()->SetTitleSize(0.05);
   hPhotonAuConverted__7->GetZaxis()->SetTitleOffset(1);
   hPhotonAuConverted__7->GetZaxis()->SetTitleFont(42);
   hPhotonAuConverted__7->Draw("same");
   
   TLegend *leg = new TLegend(0.2,0.7,0.8,0.9,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(1);
   leg->SetFillColor(0);
   leg->SetFillStyle(1001);
   TLegendEntry *entry=leg->AddEntry("NULL","Fun4All-EIC simulation","h");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hPhotonAuConverted","Interacted with 2#mum Au","lf");

   ci = 1182;
   color = new TColor(ci, 0.6, 0, 0, " ", 0.3);
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#990000");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hPhotonBe","Interacted with 760#mum Be","lf");

   ci = 1180;
   color = new TColor(ci, 0, 0.6, 0, " ", 0.3);
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#009900");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("hPhotonSilicon","Interacted with 300#mum Si","lf");

   ci = 1181;
   color = new TColor(ci, 0, 0, 0.6, " ", 0.3);
   entry->SetFillColor(ci);
   entry->SetFillStyle(1001);

   ci = TColor::GetColor("#000099");
   entry->SetLineColor(ci);
   entry->SetLineStyle(1);
   entry->SetLineWidth(2);
   entry->SetMarkerColor(1);
   entry->SetMarkerStyle(21);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   PhotonConversion_1->Modified();
   PhotonConversion->cd();
   PhotonConversion->Modified();
   PhotonConversion->cd();
   PhotonConversion->SetSelected(PhotonConversion);
}
